name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            set -e

            VERSION=v${{ github.run_number }}

            cd ~/Sample-for-linux-labs-

            echo "Pulling latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Building Docker image with version: $VERSION"
            docker build -t simple-cicd-app:$VERSION .

            echo "Tagging latest..."
            docker tag simple-cicd-app:$VERSION simple-cicd-app:latest

            echo "Stopping old container..."
            docker stop simple-app || true
            docker rm simple-app || true

            echo "Starting new container..."
            if docker run -d \
                --name simple-app \
                -p 3000:3000 \
                --restart unless-stopped \
                simple-cicd-app:$VERSION
            then
                echo "Deployment Successful - $VERSION"

            else
                echo "Deployment Failed - rolling back"

                docker rm -f simple-app || true

                docker run -d \
                    --name simple-app \
                    -p 3000:3000 \
                    simple-cicd-app:latest || true

                exit 1
            fi
